### ISSUE TITLE
Receiving NoMethodError(undefined method 'tags' for #<ActiveSupport::Logger>')

### ISSUE THREAD

**Issue by dchersey** [rails/actioncable#121]
Hello, setting this up for the first time following examples at http://nithinbekal.com/posts/rails-action-cable/ using latest master branch commit. Everything seems to be working fine rails-side and javascript client-side; I'm hitting all my breakpoints on the publish and subscriber code except I'm not receiving any data to the client.  

I'm launching a cable server with 
```bash
bundle exec puma -p 28080 cable/config.ru
```
and my config.ru contains
```ruby
require ::File.expand_path('../../config/environment',  __FILE__)
Rails.application.eager_load!

require 'action_cable/process/logging'

run ActionCable.server
```

Checking the cable server STDOUT, I see:

```
Started GET "/" [WebSocket] for 127.0.0.1 at 2015-11-12 16:10:51 -0500
127.0.0.1 - - [12/Nov/2015 16:10:51] "GET / HTTP/1.1" HIJACKED -1 0.0009
There was an exception - NoMethodError(undefined method `tags' for #<ActiveSupport::Logger:0x007fadc6052f50>)
/Users/david/projects/ia/vendor/ruby/2.2.0/bundler/gems/actioncable-63cdbf87ddae/lib/action_cable/server/worker/active_record_connection_management.rb:15:in `with_database_connections'
/Users/david/projects/ia/vendor/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/Users/david/projects/ia/vendor/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:342:in `call'
/Users/david/projects/ia/vendor/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:342:in `block in simple'
/Users/david/projects/ia/vendor/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:497:in `call'
/Users/david/projects/ia/vendor/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:497:in `block in around'
/Users/david/projects/ia/vendor/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/Users/david/projects/ia/vendor/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/Users/david/projects/ia/vendor/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/Users/david/projects/ia/vendor/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_work_callbacks'
/Users/david/projects/ia/vendor/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/david/projects/ia/vendor/ruby/2.2.0/bundler/gems/actioncable-63cdbf87ddae/lib/action_cable/server/worker.rb:18:in `invoke'
```

Am I missing a dependency or configuration? I checked into ActiveSupport::TaggedLogging and I don't see a tags property or method.  My Gemfile.Lock shows ActiveSupport 4.2.4 and also:
```ruby
GIT
  remote: git://github.com/rails/actioncable.git
  revision: 63cdbf87ddaeb6bbc852de7ca2c504b7f6a22321
  specs:
    actioncable (0.0.3)
      actionpack (>= 4.2.0)
      activesupport (>= 4.2.0)
      celluloid (~> 0.16.0)
      coffee-rails
      em-hiredis (~> 0.3.0)
      faye-websocket (~> 0.10.0)
      redis (~> 3.0)
      websocket-driver (~> 0.6.1)

GEM
  remote: https://rubygems.org/
  specs:
    actionmailer (4.2.4)
      actionpack (= 4.2.4)
      actionview (= 4.2.4)
      activejob (= 4.2.4)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.4)
      actionview (= 4.2.4)
      activesupport (= 4.2.4)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (4.2.4)
      activesupport (= 4.2.4)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    active_model_serializers (0.9.3)
      activemodel (>= 3.2)
    activejob (4.2.4)
      activesupport (= 4.2.4)
      globalid (>= 0.3.0)
    activemodel (4.2.4)
      activesupport (= 4.2.4)
      builder (~> 3.1)
    activerecord (4.2.4)
      activemodel (= 4.2.4)
      activesupport (= 4.2.4)
      arel (~> 6.0)
    activesupport (4.2.4)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    addressable (2.3.8)
    airbrake (3.2.1)
      builder
      multi_json
    arel (6.0.3)
    awesome_print (1.6.1)
    backports (3.6.7)
    bcrypt (3.1.10)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    builder (3.2.2)
    byebug (8.1.0)
    cancancan (1.13.1)
    capistrano (3.4.0)
      i18n
      rake (>= 10.0.0)
      sshkit (~> 1.3)
    capistrano-bower (1.1.0)
      capistrano (~> 3.0)
    capistrano-bundler (1.1.4)
      capistrano (~> 3.1)
      sshkit (~> 1.2)
    capistrano-ember_cli (1.0.0)
      capistrano (~> 3.0)
    capistrano-npm (1.0.1)
      capistrano (>= 3.0.0)
    capistrano-nvm (0.0.6)
      capistrano (~> 3.1)
    capistrano-rails (1.1.5)
      capistrano (~> 3.1)
      capistrano-bundler (~> 1.1)
    capistrano-rvm (0.1.2)
      capistrano (~> 3.0)
      sshkit (~> 1.2)
    capistrano-service (0.0.2)
      capistrano (>= 3.0.0.pre)
    capybara (2.5.0)
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    capybara-webkit (1.7.1)
      capybara (>= 2.3.0, < 2.6.0)
      json
    celluloid (0.16.0)
      timers (~> 4.0.0)
    coderay (1.1.0)
    coffee-rails (4.1.0)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.9.1.1)
    colorize (0.7.7)
    connection_pool (2.2.0)
    css_parser (1.3.7)
      addressable
    dalli (2.7.4)
    database_cleaner (1.5.1)
    debug_inspector (0.0.2)
    devise (3.5.2)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      responders
      thread_safe (~> 0.1)
      warden (~> 1.2.3)
    devise-async (0.10.1)
      devise (~> 3.2)
    diff-lcs (1.2.5)
    docile (1.1.5)
    draper (2.1.0)
      actionpack (>= 3.0)
      activemodel (>= 3.0)
      activesupport (>= 3.0)
      request_store (~> 1.0)
    em-hiredis (0.3.0)
      eventmachine (~> 1.0)
      hiredis (~> 0.5.0)
    erubis (2.7.0)
    eventmachine (1.0.8)
    execjs (2.6.0)
    factory_girl (4.5.0)
      activesupport (>= 3.0.0)
    factory_girl_rails (4.5.0)
      factory_girl (~> 4.5.0)
      railties (>= 3.0.0)
    faraday (0.9.2)
      multipart-post (>= 1.2, < 3)
    faye-websocket (0.10.1)
      eventmachine (>= 0.12.0)
      websocket-driver (>= 0.5.1)
    ffaker (2.1.0)
    ffi (1.9.10)
    font-awesome-rails (4.4.0.0)
      railties (>= 3.2, < 5.0)
    formatador (0.2.5)
    foundation-rails (5.5.3.2)
      railties (>= 3.1.0)
      sass (>= 3.3.0, < 3.5)
    fuubar (2.0.0)
      rspec (~> 3.0)
      ruby-progressbar (~> 1.4)
    globalid (0.3.6)
      activesupport (>= 4.1.0)
    guard (2.13.0)
      formatador (>= 0.2.4)
      listen (>= 2.7, <= 4.0)
      lumberjack (~> 1.0)
      nenv (~> 0.1)
      notiffany (~> 0.0)
      pry (>= 0.9.12)
      shellany (~> 0.0)
      thor (>= 0.18.1)
    guard-bundler (2.1.0)
      bundler (~> 1.0)
      guard (~> 2.2)
      guard-compat (~> 1.1)
    guard-compat (1.2.1)
    guard-migrate (1.2.1)
      activerecord (>= 4.1.0)
      guard (~> 2.3)
      guard-compat (~> 1.1)
    guard-rspec (4.6.4)
      guard (~> 2.1)
      guard-compat (~> 1.1)
      rspec (>= 2.99.0, < 4.0)
    haml (4.0.7)
      tilt
    haml-rails (0.9.0)
      actionpack (>= 4.0.1)
      activesupport (>= 4.0.1)
      haml (>= 4.0.6, < 5.0)
      html2haml (>= 1.0.1)
      railties (>= 4.0.1)
    hashie (3.4.3)
    headjs-rails (0.4.2)
      rails (>= 3.0.0)
    hiredis (0.5.2)
    hitimes (1.2.3)
    html2haml (2.0.0)
      erubis (~> 2.7.0)
      haml (~> 4.0.0)
      nokogiri (~> 1.6.0)
      ruby_parser (~> 3.5)
    htmlentities (4.3.4)
    i18n (0.7.0)
    interactor (3.1.0)
    interactor-rails (2.0.1)
      interactor (~> 3.0)
      rails (>= 3, < 5)
    jquery-minicolors-rails (2.1.4.0)
      jquery-rails
      rails (>= 3.2.8)
    jquery-rails (4.0.5)
      rails-dom-testing (~> 1.0)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    jquery-turbolinks (2.1.0)
      railties (>= 3.1.0)
      turbolinks
    jquery-ui-rails (5.0.5)
      railties (>= 3.2.16)
    json (1.8.3)
    json_spec (1.1.4)
      multi_json (~> 1.0)
      rspec (>= 2.0, < 4.0)
    jwt (1.5.2)
    kaminari (0.16.3)
      actionpack (>= 3.0.0)
      activesupport (>= 3.0.0)
    kgio (2.10.0)
    listen (3.0.4)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    lumberjack (1.0.9)
    mail (2.6.3)
      mime-types (>= 1.16, < 3)
    memcachier (0.0.2)
    method_source (0.8.2)
    mime-types (2.6.2)
    mini_portile (0.6.2)
    minitest (5.8.2)
    multi_json (1.11.2)
    multi_xml (0.5.5)
    multipart-post (2.0.0)
    nenv (0.2.0)
    nested_form (0.3.2)
    net-scp (1.2.1)
      net-ssh (>= 2.6.5)
    net-ssh (3.0.1)
    nokogiri (1.6.6.2)
      mini_portile (~> 0.6.0)
    notiffany (0.0.8)
      nenv (~> 0.1)
      shellany (~> 0.0)
    nprogress-rails (0.1.6.7)
    oauth (0.4.7)
    oauth2 (1.0.0)
      faraday (>= 0.8, < 0.10)
      jwt (~> 1.0)
      multi_json (~> 1.3)
      multi_xml (~> 0.5)
      rack (~> 1.2)
    omniauth (1.2.2)
      hashie (>= 1.2, < 4)
      rack (~> 1.0)
    omniauth-facebook (3.0.0)
      omniauth-oauth2 (~> 1.2)
    omniauth-oauth (1.1.0)
      oauth
      omniauth (~> 1.0)
    omniauth-oauth2 (1.4.0)
      oauth2 (~> 1.0)
      omniauth (~> 1.2)
    omniauth-twitter (1.2.1)
      json (~> 1.3)
      omniauth-oauth (~> 1.1)
    orm_adapter (0.5.0)
    pg (0.18.3)
    polyamorous (1.1.0)
      activerecord (>= 3.0)
    premailer (1.8.6)
      css_parser (>= 1.3.6)
      htmlentities (>= 4.0.0)
    premailer-rails (1.8.2)
      actionmailer (>= 3, < 5)
      premailer (~> 1.7, >= 1.7.9)
    pry (0.10.3)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    pry-byebug (3.3.0)
      byebug (~> 8.0)
      pry (~> 0.10)
    pry-rails (0.3.4)
      pry (>= 0.9.10)
    pry-stack_explorer (0.4.9.2)
      binding_of_caller (>= 0.7)
      pry (>= 0.9.11)
    puma (2.15.3)
    quiet_assets (1.1.0)
      railties (>= 3.1, < 5.0)
    rack (1.6.4)
    rack-cors (0.4.0)
    rack-pjax (0.8.0)
      nokogiri (~> 1.5)
      rack (~> 1.1)
    rack-protection (1.5.3)
      rack
    rack-test (0.6.3)
      rack (>= 1.0)
    rack-timeout (0.1.2)
    rails (4.2.4)
      actionmailer (= 4.2.4)
      actionpack (= 4.2.4)
      actionview (= 4.2.4)
      activejob (= 4.2.4)
      activemodel (= 4.2.4)
      activerecord (= 4.2.4)
      activesupport (= 4.2.4)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.4)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.7)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6.0)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.2)
      loofah (~> 2.0)
    rails_12factor (0.0.3)
      rails_serve_static_assets
      rails_stdout_logging
    rails_admin (0.7.0)
      builder (~> 3.1)
      coffee-rails (~> 4.0)
      font-awesome-rails (>= 3.0, < 5)
      haml (~> 4.0)
      jquery-rails (>= 3.0, < 5)
      jquery-ui-rails (~> 5.0)
      kaminari (~> 0.14)
      nested_form (~> 0.3)
      rack-pjax (~> 0.7)
      rails (~> 4.0)
      remotipart (~> 1.0)
      safe_yaml (~> 1.0)
      sass-rails (>= 4.0, < 6)
    rails_serve_static_assets (0.0.4)
    rails_stdout_logging (0.0.4)
    railties (4.2.4)
      actionpack (= 4.2.4)
      activesupport (= 4.2.4)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    raindrops (0.15.0)
    rake (10.4.2)
    rb-fsevent (0.9.6)
    rb-inotify (0.9.5)
      ffi (>= 0.5.0)
    rdoc (4.2.0)
    redis (3.2.1)
    redis-browser (0.3.2)
      coffee-script
      multi_json
      redis
      sass
      sinatra
      sinatra-contrib
      slim
    redis-namespace (1.5.2)
      redis (~> 3.0, >= 3.0.4)
    remotipart (1.2.1)
    request_store (1.2.0)
    responders (2.1.0)
      railties (>= 4.2.0, < 5)
    rspec (3.3.0)
      rspec-core (~> 3.3.0)
      rspec-expectations (~> 3.3.0)
      rspec-mocks (~> 3.3.0)
    rspec-activemodel-mocks (1.0.2)
      activemodel (>= 3.0)
      activesupport (>= 3.0)
      rspec-mocks (>= 2.99, < 4.0)
    rspec-core (3.3.2)
      rspec-support (~> 3.3.0)
    rspec-expectations (3.3.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.3.0)
    rspec-mocks (3.3.2)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.3.0)
    rspec-rails (3.3.3)
      actionpack (>= 3.0, < 4.3)
      activesupport (>= 3.0, < 4.3)
      railties (>= 3.0, < 4.3)
      rspec-core (~> 3.3.0)
      rspec-expectations (~> 3.3.0)
      rspec-mocks (~> 3.3.0)
      rspec-support (~> 3.3.0)
    rspec-sidekiq (2.1.0)
      rspec (~> 3.0, >= 3.0.0)
      sidekiq (>= 2.4.0)
    rspec-support (3.3.0)
    rspec_junit_formatter (0.2.3)
      builder (< 4)
      rspec-core (>= 2, < 4, != 2.12.0)
    ruby-progressbar (1.7.5)
    ruby_parser (3.7.2)
      sexp_processor (~> 4.1)
    safe_yaml (1.0.4)
    sass (3.4.19)
    sass-rails (5.0.4)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    sdoc (0.4.1)
      json (~> 1.7, >= 1.7.7)
      rdoc (~> 4.0)
    settingslogic (2.0.9)
    sexp_processor (4.6.0)
    shellany (0.0.1)
    shoulda-matchers (3.0.1)
      activesupport (>= 4.0.0)
    sidekiq (3.4.2)
      celluloid (~> 0.16.0)
      connection_pool (~> 2.2, >= 2.2.0)
      json (~> 1.0)
      redis (~> 3.2, >= 3.2.1)
      redis-namespace (~> 1.5, >= 1.5.2)
    simple_form (3.2.0)
      actionpack (~> 4.0)
      activemodel (~> 4.0)
    simplecov (0.10.0)
      docile (~> 1.1.0)
      json (~> 1.8)
      simplecov-html (~> 0.10.0)
    simplecov-html (0.10.0)
    sinatra (1.4.6)
      rack (~> 1.4)
      rack-protection (~> 1.4)
      tilt (>= 1.3, < 3)
    sinatra-contrib (1.4.6)
      backports (>= 2.0)
      multi_json
      rack-protection
      rack-test
      sinatra (~> 1.4.0)
      tilt (>= 1.3, < 3)
    slim (3.0.6)
      temple (~> 0.7.3)
      tilt (>= 1.3.3, < 2.1)
    slop (3.6.0)
    spring (1.4.1)
    spring-commands-rspec (1.0.4)
      spring (>= 0.9.1)
    sprockets (3.4.0)
      rack (> 1, < 3)
    sprockets-rails (2.3.3)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (>= 2.8, < 4.0)
    squeel (1.2.3)
      activerecord (>= 3.0)
      activesupport (>= 3.0)
      polyamorous (~> 1.1.0)
    sshkit (1.7.1)
      colorize (>= 0.7.0)
      net-scp (>= 1.1.2)
      net-ssh (>= 2.8.0)
    temple (0.7.6)
    terminal-notifier (1.6.3)
    terminal-notifier-guard (1.6.4)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (2.0.1)
    timers (4.0.4)
      hitimes
    turbolinks (2.5.3)
      coffee-rails
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.7.2)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    unicorn (5.0.0)
      kgio (~> 2.6)
      rack
      raindrops (~> 0.7)
    warden (1.2.3)
      rack (>= 1.0)
    websocket-driver (0.6.3)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.2)
    xpath (2.0.0)
      nokogiri (~> 1.3)

PLATFORMS
  ruby

DEPENDENCIES
  actioncable!
  active_model_serializers
  addressable
  airbrake (~> 3.2.1)
  awesome_print
  cancancan (~> 1.9)
  capistrano
  capistrano-bower
  capistrano-bundler
  capistrano-ember_cli
  capistrano-npm
  capistrano-nvm
  capistrano-rails
  capistrano-rvm
  capistrano-service
  capybara-webkit
  coffee-rails
  dalli
  database_cleaner
  devise
  devise-async
  draper
  factory_girl_rails
  ffaker
  foundation-rails
  fuubar
  guard-bundler
  guard-migrate
  guard-rspec
  haml-rails
  headjs-rails
  interactor
  interactor-rails
  jquery-minicolors-rails
  jquery-rails
  jquery-turbolinks
  json_spec
  memcachier
  minitest
  nprogress-rails
  omniauth
  omniauth-facebook
  omniauth-twitter
  pg
  premailer-rails
  pry-byebug
  pry-rails
  pry-stack_explorer
  puma
  quiet_assets
  rack-cors
  rack-timeout (~> 0.1.0beta4)
  rails (~> 4.2.3)
  rails_12factor
  rails_admin
  rb-fsevent
  redis
  redis-browser
  rspec-activemodel-mocks
  rspec-mocks
  rspec-rails
  rspec-sidekiq
  rspec_junit_formatter
  sass-rails
  sdoc
  settingslogic
  shoulda-matchers
  sidekiq
  simple_form
  simplecov
  sinatra
  spring
  spring-commands-rspec
  squeel
  terminal-notifier
  terminal-notifier-guard
  turbolinks
  uglifier
  unicorn

BUNDLED WITH
   1.10.5
````

**Comment by dchersey** [comment]
update: I have switched to rails (5) edge -- working now.

**Comment by benams** [comment]
Is that mean the bug is closed? What about rails 4? Furthermore, what if I use a logger other than ActiveSupport::Logger (I use 'logging' gem for example)?

**Comment by dchersey** [comment]
I would not say so; seems like action-cable is broken right now with Rails 4.2.4.

**Comment by lsylvester** [comment]
I was not able to get this error happening on rails 4.2 using the default logger, but using a custom logger caused it to get this error. Any change a custom logger was being used when you were running on 4.2?

**Comment by benams** [comment]
Yes, my app uses the "logging" gem. Do you think rolling back to the default logger will be enough? you can use action cable properly with rails 4.2 + default logger?

**Comment by dchersey** [comment]
I was also able to get everything working by starting from scratch with a new rails app ... I will be bringing in the other configuration changes/additional gems gradually to find the breaking issue and will update this thread when I find it. I am not aware of using a custom logger but I was using the [Rails4StarterKit](https://github.com/starterkits/rails4-starterkit) and there may be something in there I am not aware of. 

Stay tuned...

**Comment by lsylvester** [comment]
@dchersey It looks like Rails4StarterKit uses a custom logger defined at https://github.com/starterkits/rails4-starterkit/blob/master/config/environments/development.rb#L18, so that would explain the errors you were getting.

**Comment by dchersey** [comment]
Ah yes ... I see it now :)
