### ISSUE TITLE
Rack app error: #<NoMethodError: undefined method `+' for nil:NilClass>

### ISSUE THREAD

**Issue by zcpdog** [rails/actioncable#67]
Hi, 
I setup actioncable in production, after serval hours running, I got many the following errors, 
I am using : 
rails 4.2  ruby 2.2.1 
puma + nginx
 
```
2015-08-23 15:14:42 +0800: Rack app error: #<NoMethodError: undefined method `+' for nil:NilClass>
/home/littlefire/var/www/apps/littlefire/shared/bundle/ruby/2.2.0/gems/websocket-driver-0.6.2/lib/websocket/driver/hybi.rb:11:in `generate_accept'
/home/littlefire/var/www/apps/littlefire/shared/bundle/ruby/2.2.0/gems/websocket-driver-0.6.2/lib/websocket/driver/hybi.rb:74:in `initialize'
/home/littlefire/var/www/apps/littlefire/shared/bundle/ruby/2.2.0/gems/websocket-driver-0.6.2/lib/websocket/driver.rb:149:in `new'
/home/littlefire/var/www/apps/littlefire/shared/bundle/ruby/2.2.0/gems/websocket-driver-0.6.2/lib/websocket/driver.rb:149:in `rack'
/home/littlefire/var/www/apps/littlefire/shared/bundle/ruby/2.2.0/gems/faye-websocket-0.10.0/lib/faye/websocket.rb:69:in `initialize'
/home/littlefire/var/www/apps/littlefire/shared/bundle/ruby/2.2.0/bundler/gems/actioncable-6143352f8ffb/lib/action_cable/connection/web_socket.rb:8:in `new'
/home/littlefire/var/www/apps/littlefire/shared/bundle/ruby/2.2.0/bundler/gems/actioncable-6143352f8ffb/lib/action_cable/connection/web_socket.rb:8:in `initialize'
/home/littlefire/var/www/apps/littlefire/shared/bundle/ruby/2.2.0/bundler/gems/actioncable-6143352f8ffb/lib/action_cable/connection/base.rb:61:in `new'
/home/littlefire/var/www/apps/littlefire/shared/bundle/ruby/2.2.0/bundler/gems/actioncable-6143352f8ffb/lib/action_cable/connection/base.rb:61:in `initialize'
/home/littlefire/var/www/apps/littlefire/shared/bundle/ruby/2.2.0/bundler/gems/actioncable-6143352f8ffb/lib/action_cable/server/base.rb:21:in `new'
/home/littlefire/var/www/apps/littlefire/shared/bundle/ruby/2.2.0/bundler/gems/actioncable-6143352f8ffb/lib/action_cable/server/base.rb:21:in `call'
/home/littlefire/var/www/apps/littlefire/shared/bundle/ruby/2.2.0/gems/puma-2.13.4/lib/puma/configuration.rb:78:in `call'
/home/littlefire/var/www/apps/littlefire/shared/bundle/ruby/2.2.0/gems/puma-2.13.4/lib/puma/server.rb:541:in `handle_request'
/home/littlefire/var/www/apps/littlefire/shared/bundle/ruby/2.2.0/gems/puma-2.13.4/lib/puma/server.rb:388:in `process_client'
/home/littlefire/var/www/apps/littlefire/shared/bundle/ruby/2.2.0/gems/puma-2.13.4/lib/puma/server.rb:270:in `block in run'
/home/littlefire/var/www/apps/littlefire/shared/bundle/ruby/2.2.0/gems/puma-2.13.4/lib/puma/thread_pool.rb:106:in `call'
/home/littlefire/var/www/apps/littlefire/shared/bundle/ruby/2.2.0/gems/puma-2.13.4/lib/puma/thread_pool.rb:106:in `block in spawn_thread'
```

any help will be appreciated 

Thanks

**Comment by kaichen** [comment]
It looks like a configuration problem. Could you provide any puma config or its launch options?

**Comment by zcpdog** [comment]
Hi Kai, 
Thanks again for your quick response, 

here is the puma.rb under shared directory 

```
#!/usr/bin/env puma

directory '/home/littlefire/var/www/apps/littlefire/current'
rackup "/home/littlefire/var/www/apps/littlefire/current/cable/config.ru"
environment 'production'

pidfile "/home/littlefire/var/www/apps/littlefire/shared/tmp/pids/puma.pid"
state_path "/home/littlefire/var/www/apps/littlefire/shared/tmp/pids/puma.state"
stdout_redirect '/home/littlefire/var/www/apps/littlefire/shared/log/puma_access.log', '/home/littlefire/var/www/apps/littlefire/shared/log/puma_error.log', true


threads 0,16

bind 'unix:///home/littlefire/var/www/apps/littlefire/shared/tmp/sockets/puma.sock'

workers 0



prune_bundler


on_restart do
  puts 'Refreshing Gemfile'
  ENV["BUNDLE_GEMFILE"] = "/home/littlefire/var/www/apps/littlefire/current/Gemfile"
end
```

**Comment by lsylvester** [comment]
It looks like this error will occur when `env['HTTP_SEC_WEBSOCKET_VERSION']` is set but  `env['HTTP_SEC_WEBSOCKET_KEY']` is not set. 

According to https://github.com/jrief/django-websocket-redis/issues/54, this can happen for old ios devices. Are you able to tell what device is making the erroring requests? Can you confirm headers that are being sent in those requests?
